version: "3.1"

services:
  db:
    image: postgres:17-alpine
    container_name: fsecommerce-db
    environment:
      POSTGRES_DB: fsecommerce
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"