services:
  db:
    image: postgres:17-alpine
    container_name: fsecommerce-db
    environment:
      POSTGRES_DB: fsecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usuario -d fsecommerce" ]
      interval: 5s
      timeout: 5s
      retries: 5