services:
  db:
    image: postgres:17-alpine
    container_name: fsecommerce-db
    environment:
      POSTGRES_DB: fsecommerce
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usuario -d fsecommerce" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  k6:
    image: grafana/k6
    container_name: fsecommerce-loadtest
    volumes:
      - ./scripts:/scripts:ro
    environment:
      - BASE_URL=http://host.docker.internal:8080
    # O entrypoint chama o arquivo correto que vocÃª criou
    entrypoint: [ "k6", "run", "/scripts/stress-test.js" ]
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy

networks:
  ecommerce-network:
    driver: bridge