name: Java CI with E2E and Load Tests

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: fsecommerce
          POSTGRES_USER: usuario
          POSTGRES_PASSWORD: senha
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Otimiza o tempo instalando do cache se nada mudou

      - name: Install Dependencies
        # Instala as dependências da raiz (onde está seu package-lock.json)
        run: npm ci

      - name: Run Unit & Integration Tests (Maven)
        run: mvn test

      - name: Build and Start Spring Boot App
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fsecommerce
          SPRING_DATASOURCE_USERNAME: usuario
          SPRING_DATASOURCE_PASSWORD: senha
        run: |
          mvn clean package -DskipTests
          java -jar target/*.jar &
          # Espera a API e o Actuator ficarem prontos
          npx wait-on http://localhost:8080/fsecommerce/actuator/health --timeout 60000 

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # 'project' indica onde está o cypress.config.js
          project: ./src/test/resources/cypress
          install: false
          browser: chrome
        env:
          CYPRESS_BASE_URL: http://localhost:8080/fsecommerce

      - name: Run k6 Stress Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: src/test/resources/k6/scripts/stress-test.js
        env:
          BASE_URL: http://localhost:8080/fsecommerce